#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path


PROJECT_LAYOUT = [
    ("AGF_PROJECT_MCP_HUB", "MCP_Hub"),
    ("AGF_PROJECT_3_5", "Project3.5"),
    ("AGF_PROJECT_4", "Project4"),
    ("AGF_PROJECT_5", "Project5"),
    ("AGF_PROJECT_5_5", "Project 5.5"),
    ("AGF_PROJECT_DESIGN", "Project Design"),
]

PLACEHOLDER_GEMINI_RULE = """# Gemini Shared Context

- This file was seeded by `bootstrap_shared_fabric.py`.
- Replace this placeholder with your real global Gemini rule set when available.
"""


def expand_path(value: str | Path) -> Path:
    return Path(value).expanduser().resolve()


def prompt_path(label: str, default: Path, interactive: bool) -> Path:
    if not interactive:
        return default
    raw = input(f"{label} [{default}]: ").strip()
    return expand_path(raw) if raw else default


def derive_values(args: argparse.Namespace) -> dict[str, str]:
    repo_root = Path(__file__).resolve().parents[1]
    interactive = not args.non_interactive and sys.stdin.isatty()

    user_home = prompt_path("User home", expand_path(args.user_home or Path.home()), interactive)
    desktop_root = prompt_path(
        "Desktop root",
        expand_path(args.desktop_root or (user_home / "Desktop")),
        interactive,
    )
    framework_source_root = prompt_path(
        "Framework source root",
        expand_path(args.framework_source_root or (repo_root / "fabric")),
        interactive,
    )
    global_root = prompt_path(
        "Shared fabric global root",
        expand_path(args.global_root or (user_home / "Antigravity_Skills" / "global-agent-fabric")),
        interactive,
    )
    awesome_skills_root = prompt_path(
        "Awesome skills root",
        expand_path(args.awesome_skills_root or (user_home / "Antigravity_Skills" / "awesome-skills")),
        interactive,
    )
    gemini_root = prompt_path(
        "Gemini root",
        expand_path(args.gemini_root or (user_home / ".gemini")),
        interactive,
    )
    codex_root = prompt_path(
        "Codex root",
        expand_path(args.codex_root or (user_home / ".codex")),
        interactive,
    )

    antigravity_root = gemini_root / "antigravity"
    values = {
        "AGF_USER_HOME": str(user_home),
        "AGF_DESKTOP_ROOT": str(desktop_root),
        "AGF_FRAMEWORK_SOURCE_ROOT": str(framework_source_root),
        "AGF_GLOBAL_ROOT": str(global_root),
        "AGF_AWESOME_SKILLS_ROOT": str(awesome_skills_root),
        "AGF_GEMINI_ROOT": str(gemini_root),
        "AGF_GEMINI_SETTINGS": str(expand_path(args.gemini_settings or (gemini_root / "settings.json"))),
        "AGF_GEMINI_RULE": str(expand_path(args.gemini_rule or (gemini_root / "GEMINI.md"))),
        "AGF_ANTIGRAVITY_MCP_CONFIG": str(
            expand_path(args.antigravity_mcp_config or (antigravity_root / "mcp_config.json"))
        ),
        "AGF_ANTIGRAVITY_BRAIN_ROOT": str(
            expand_path(args.antigravity_brain_root or (antigravity_root / "brain"))
        ),
        "AGF_ANTIGRAVITY_HISTORY_ROOT": str(
            expand_path(
                args.antigravity_history_root
                or (user_home / "Library" / "Application Support" / "Antigravity" / "User" / "History")
            )
        ),
        "AGF_CODEX_ROOT": str(codex_root),
    }
    for key, directory_name in PROJECT_LAYOUT:
        values[key] = str(desktop_root / directory_name)
    return values


def render_env_file(values: dict[str, str]) -> str:
    lines = ["# Generated by install/bootstrap_shared_fabric.py", ""]
    for key in [
        "AGF_USER_HOME",
        "AGF_DESKTOP_ROOT",
        "AGF_FRAMEWORK_SOURCE_ROOT",
        "AGF_GLOBAL_ROOT",
        "AGF_AWESOME_SKILLS_ROOT",
        "AGF_GEMINI_ROOT",
        "AGF_GEMINI_SETTINGS",
        "AGF_GEMINI_RULE",
        "AGF_ANTIGRAVITY_MCP_CONFIG",
        "AGF_ANTIGRAVITY_BRAIN_ROOT",
        "AGF_ANTIGRAVITY_HISTORY_ROOT",
        "AGF_CODEX_ROOT",
        "AGF_PROJECT_MCP_HUB",
        "AGF_PROJECT_3_5",
        "AGF_PROJECT_4",
        "AGF_PROJECT_5",
        "AGF_PROJECT_5_5",
        "AGF_PROJECT_DESIGN",
    ]:
        lines.append(f'{key}="{values[key]}"')
    lines.append("")
    return "\n".join(lines)


def ensure_json(path: Path, payload: dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists():
        path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def ensure_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists():
        path.write_text(content.rstrip() + "\n", encoding="utf-8")


def ensure_layout(values: dict[str, str]) -> list[str]:
    created: list[str] = []

    def mkdir(path: Path) -> None:
        if not path.exists():
            path.mkdir(parents=True, exist_ok=True)
            created.append(str(path))

    framework_source_root = expand_path(values["AGF_FRAMEWORK_SOURCE_ROOT"])
    required_snapshot_files = [
        framework_source_root / "scripts" / "sync" / "bootstrap_global_agent_fabric.py",
        framework_source_root / "scripts" / "sync" / "preflight_check.py",
        framework_source_root / "scripts" / "sync" / "sync_all.py",
        framework_source_root / "scripts" / "sync" / "export_codex_context.py",
        framework_source_root / "sync" / "boot-sequence.md",
        framework_source_root / "memory" / "architecture.md",
        framework_source_root / "memory" / "schema.yaml",
    ]
    missing = [str(path) for path in required_snapshot_files if not path.exists()]
    if missing:
        raise SystemExit(
            "Framework source root is missing required bootstrap assets:\n" + "\n".join(missing)
        )

    mkdir(expand_path(values["AGF_GLOBAL_ROOT"]))
    mkdir(expand_path(values["AGF_AWESOME_SKILLS_ROOT"]))
    mkdir(expand_path(values["AGF_AWESOME_SKILLS_ROOT"]) / "skills")
    mkdir(expand_path(values["AGF_AWESOME_SKILLS_ROOT"]) / "data")
    mkdir(expand_path(values["AGF_AWESOME_SKILLS_ROOT"]) / "docs" / "users")
    mkdir(expand_path(values["AGF_GEMINI_ROOT"]))
    mkdir(expand_path(values["AGF_CODEX_ROOT"]))
    mkdir(expand_path(values["AGF_ANTIGRAVITY_BRAIN_ROOT"]))
    mkdir(expand_path(values["AGF_ANTIGRAVITY_HISTORY_ROOT"]))

    for key, _directory_name in PROJECT_LAYOUT:
        workspace = expand_path(values[key])
        mkdir(workspace)
        mkdir(workspace / ".agents")

    ensure_text(expand_path(values["AGF_GEMINI_RULE"]), PLACEHOLDER_GEMINI_RULE)
    ensure_json(expand_path(values["AGF_GEMINI_SETTINGS"]), {})
    ensure_json(expand_path(values["AGF_ANTIGRAVITY_MCP_CONFIG"]), {"mcpServers": {}})
    return created


def build_install_command(env_file: Path, paths_output: Path, state_archive: Path | None) -> list[str]:
    command = [
        "/bin/zsh",
        str(Path(__file__).resolve().parent / "install_everything.sh"),
        str(env_file),
        str(paths_output),
    ]
    if state_archive is not None:
        command.append(str(state_archive))
    return command


def main() -> int:
    parser = argparse.ArgumentParser(description="One-click setup for a new shared fabric storage root.")
    parser.add_argument("--env-file", type=Path, default=None)
    parser.add_argument("--paths-output", type=Path, default=None)
    parser.add_argument("--state-archive", type=Path, default=None)
    parser.add_argument("--user-home", type=Path, default=None)
    parser.add_argument("--desktop-root", type=Path, default=None)
    parser.add_argument("--framework-source-root", type=Path, default=None)
    parser.add_argument("--global-root", type=Path, default=None)
    parser.add_argument("--awesome-skills-root", type=Path, default=None)
    parser.add_argument("--gemini-root", type=Path, default=None)
    parser.add_argument("--gemini-settings", type=Path, default=None)
    parser.add_argument("--gemini-rule", type=Path, default=None)
    parser.add_argument("--antigravity-mcp-config", type=Path, default=None)
    parser.add_argument("--antigravity-brain-root", type=Path, default=None)
    parser.add_argument("--antigravity-history-root", type=Path, default=None)
    parser.add_argument("--codex-root", type=Path, default=None)
    parser.add_argument("--non-interactive", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    env_file = expand_path(args.env_file or (Path(__file__).resolve().parent / ".env.local"))
    paths_output = expand_path(args.paths_output or (Path(__file__).resolve().parent / "paths.yaml"))
    state_archive = expand_path(args.state_archive) if args.state_archive else None

    values = derive_values(args)
    created_paths = ensure_layout(values)

    env_file.parent.mkdir(parents=True, exist_ok=True)
    env_file.write_text(render_env_file(values), encoding="utf-8")
    command = build_install_command(env_file, paths_output, state_archive)

    if args.dry_run:
        print(
            json.dumps(
                {
                    "status": "dry_run",
                    "env_file": str(env_file),
                    "paths_output": str(paths_output),
                    "created_paths": created_paths,
                    "command": command,
                    "global_root": values["AGF_GLOBAL_ROOT"],
                },
                ensure_ascii=False,
                indent=2,
            )
        )
        return 0

    subprocess.run(command, check=True)
    print(
        json.dumps(
            {
                "status": "ok",
                "env_file": str(env_file),
                "paths_output": str(paths_output),
                "global_root": values["AGF_GLOBAL_ROOT"],
                "created_paths": created_paths,
            },
            ensure_ascii=False,
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
